### PR TITLE
create new project for get bits from byte of holding registers

### PR DESCRIPTION
**Pull request by fmarslan**
how to use :

Step 1 : ElementGroup type selected Holding Registers
Step 2 : ElementType selected bool
Step 3 : We will write bitoffset value to Bit Offset Input Text

### CODE REVIEW

**Comment by 2mik** [comment]
I'd like to ask for some improvements:
1. Add a solution file. Probably additional directory level will be added.
2. Reference the existing Modbus protocol classes to avoid duplicating the code.

**Comment by 2mik** [comment]
3. Remove Modbus templates and the Res folder from the project.

**Comment by fmarslan** [comment]
I did commit for the community use. Your first request makes sense but other requests were very tiring for me. You will appreciate that that will not contribute to my prestige. As a result I wish you good work

**Comment by 2mik** [comment]
Sorry, I just keep the quality of the code base.

**Pull request closed without merging**
