### PR TITLE
Feature grafana issue

### PR DESCRIPTION
**Pull request by kumajaya**
Just  a quick fix, a better fix should respect Grafana timezone argument

### CODE REVIEW

**Comment by 2mik** [comment]
When more code does the same, the code becomes less readable. I can't merge this commit.

**Comment by kumajaya** [comment]
The last master branch still return incorect time to Grafana. I will push a pull request that does the same as this commit. Read Rapid SCADA data with converted Grafana time from UTC to local time, return Grafana data with converted Rapid SCADA local time to UTC.

**Comment by kumajaya** [comment]
Installed this module on 2 different computer, Windows and Ubuntu Linux and Rapid SCADA on Linux, so I can compare Grafana query inspector result easily.

**Comment by 2mik** [comment]
We fixed the time issue yesterday. You should get the changes into your repository.
The commit is https://github.com/RapidScada/scada-community/commit/027c1a0f62fd53365ff6c9e8532310ef7c50afba

**Comment by kumajaya** [comment]
> We fixed the time issue yesterday. You should get the changes into your repository.
> The commit is [027c1a0](https://github.com/RapidScada/scada-community/commit/027c1a0f62fd53365ff6c9e8532310ef7c50afba)

Even with the patch, I still got incorrect time in Grafana, shown previous 7 hours last data. My timezone +7 UTC.

**Comment by 2mik** [comment]
Please continue the forum topic by posting new incorrect response.

**Comment by greenfoxx** [comment]
Hi Kumajaya!
Many thanks, we accepted your changes in the last commit. You were right.

**Pull request closed without merging**
